= GR8 CRM - Sales/Lead User Interface Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM Sales/Lead User Interface Plugin
:keywords: groovy, grails, crm, gr8crm, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-sales-ui
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== Sales/Lead User Interface Plugin

The `crm-sales-ui` plugin provides a Twitter Bootstrap user interface for managing leads and sales opportunities.
It depends on the `crm-sales` plugin for low level services and persistence.

== Sales staff

When creating or updating a sales project you can select the responsible sales representative from a dropdown list.
This dropdown list is populated using an application event `crmTenant.getUsers`. You must add an event listener in
one of your application services that listens to this event and returns a list of users (sales staff).

For a list of *all* registered users you can add something like this to a service in your application:

[source,groovy]
.MyApplicationService.groovy
----
@Listener(namespace="crmTenant", topic="getUsers")
def listAllUsersInTenant(data) {
    CrmUserRole.createCriteria().list(sort: 'user.name', order: 'asc') {
        resultTransformer CriteriaSpecification.ALIAS_TO_ENTITY_MAP
        projections {
            user {
                property('id', 'id')
                property('guid', 'guid')
                property('username', 'username')
                property('name', 'name')
                property('email', 'email')
            }
        }
        role {
            eq('tenantId', data.tenant)
        }
    }
}
----

== Configuration

The `crm-sales-ui` plugin can be configured with the following parameters.

[options="header"]
|===
| Key                      | Description                                                   | Default value
| crm.currency.default     | Default currency code when `CrmSalesProject.currency` is null | "EUR"
| crm.sales.probabilities  | List of valid probability options (rendered in <select>)      | [0, 0.2, 0.4, 0.6, 0.8, 1]
| crm.sales.export.timeout | Timeout (in seconds) waiting for export process to finish     | 60
|===

== Changes

2.0.0:: First public release

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.
